// Generated by @mindustry-ts/codegen. Do not edit.
// Source: sample.comp.ts
/* eslint-disable */

/**
 * Position component: 2D coordinates plus a distance helper.
 */
export interface Pos {
  /** X coordinate. */
  x: number;
  /** Y coordinate. */
  y: number;
  /** Distance to another position. */
  dst(other: Pos): number;
}

/** Merged entity class for {@link Posc}. */
export class PosEntity implements Pos {
  /** X coordinate. */
  x: number = 0;
  /** Y coordinate. */
  y: number = 0;
  /** Distance to another position. */
  dst(other: Pos): number {
    const dx = this.x - other.x;
    const dy = this.y - other.y;
    return Math.sqrt(dx * dx + dy * dy);
  }
}
