import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import ts from "typescript";
import { collectModels } from "../codegen.js";
import { DEFAULT_GROUPS } from "../config.js";
import { assignClassIds, generateEntityMappingFile } from "./entityMappingGen.js";
import { EntityGenError, generateEntityFiles, mergeMethods, resolveEntities } from "./entityGen.js";
import type { ComponentModel } from "../model.js";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const fixturesRoot = path.join(packageRoot, "fixtures");

function fixtureFiles(directory: string): string[] {
  const found: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) found.push(...fixtureFiles(full));
    else if (entry.name.endsWith(".def.ts")) found.push(full);
  }
  return found.sort();
}

const model = collectModels(fixtureFiles(fixturesRoot));
const classIds = assignClassIds(model.entityDefs, fixturesRoot, new Map());
const outputs = generateEntityFiles({
  components: model.components,
  entityDefs: model.entityDefs,
  groups: DEFAULT_GROUPS,
  classIds,
  inputRoot: fixturesRoot,
});

function file(name: string): string {
  const content = outputs.get(name);
  expect(content, `expected a generated ${name}`).toBeDefined();
  return content!;
}

function parsesCleanly(name: string): void {
  const parsed = ts.createSourceFile(name, file(name), ts.ScriptTarget.Latest, true);
  const diagnostics = (parsed as unknown as { parseDiagnostics: readonly unknown[] }).parseDiagnostics;
  expect(diagnostics).toHaveLength(0);
}

/** Finds a top-level class declaration in generated text. */
function classNamed(text: string, className: string): ts.ClassDeclaration | undefined {
  const parsed = ts.createSourceFile("generated.ts", text, ts.ScriptTarget.Latest, true);
  for (const statement of parsed.statements) {
    if (ts.isClassDeclaration(statement) && statement.name?.text === className) return statement;
  }
  return undefined;
}

describe("generateEntityFiles — interface pass (EntityProcess.java:105-172)", () => {
  it("matches the golden text for the Posc interface", () => {
    // Golden. Java emits getter/setter method pairs for every field
    // (`:148-169`); TS collapses those to properties, which is the shape the ported
    // call sites use (`u.x`, not `u.x()`).
    expect(file("Posc.ts")).toBe(
      [
        "// Generated by @mindustry-ts/codegen. Do not edit.",
        "// Source: PosComp.def.ts",
        "/* eslint-disable */",
        "",
        "/**",
        " * Interface for {@link PosComp} (Java `EntityProcess.java:109-172`).",
        " * Position component: 2D world coordinates.",
        " *",
        " * Mirrors `core/src/mindustry/entities/comp/PosComp.java`. The fixture names the",
        " * component `PosComp` (like Java) and its generated interface `Posc` — the name the",
        " * 502 ported call sites already use. The `import type` points at *generated* output,",
        " * which is exactly how real components consume their role interfaces.",
        " */",
        "export interface Posc {",
        "  /**",
        "   * X coordinate, in world units.",
        "   */",
        "  x: number;",
        "  /**",
        "   * Y coordinate, in world units.",
        "   */",
        "  y: number;",
        "  /**",
        "   * Sets the position from a raw pair.",
        "   */",
        "  set(x: number, y: number): void;",
        "  /**",
        "   * Translates by a delta.",
        "   */",
        "  trns(x: number, y: number): void;",
        "  /**",
        "   * Distance to another positioned entity.",
        "   */",
        "  dst(other: Posc): number;",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("extends the interfaces of its component dependencies", () => {
    // `HealthComp implements Entityc, Posc` -> `Healthc extends Entityc, Posc`
    // (Java `getDependencies` + `addSuperinterface`, `:123-126`).
    expect(file("Healthc.ts")).toContain("export interface Healthc extends Entityc, Posc {");
    expect(file("Mechc.ts")).toContain("export interface Mechc extends Posc, Unitc, Healthc, Entityc, Teamc {");
  });

  it("skips imported fields, and emits no interface for genInterface: false", () => {
    // `TeamComp`'s x/y are `@Import`ed from PosComp (Java `:149` filters them out).
    const teamc = file("Teamc.ts");
    expect(teamc).toContain("team: number;");
    expect(teamc).not.toContain("x: number;");
    expect(teamc).not.toContain("y: number;");

    expect(outputs.has("Buildingc.ts")).toBe(false);
    expect(outputs.has("Building.ts")).toBe(true);
  });

  it("emits the interface when genInterface is flipped (counterfactual)", () => {
    const flipped: ComponentModel[] = model.components.map((component) =>
      component.compName === "BuildingComp" ? { ...component, genInterface: true } : component,
    );
    const other = generateEntityFiles({
      components: flipped,
      entityDefs: model.entityDefs,
      groups: DEFAULT_GROUPS,
      classIds,
      inputRoot: fixturesRoot,
    });
    expect(other.has("Buildingc.ts")).toBe(true);
  });

  it("emits only syntactically valid files", () => {
    for (const name of outputs.keys()) {
      if (name === "EntityMapping.ts") continue; // generated by entityMappingGen, not here
      parsesCleanly(name);
    }
  });
});

describe("generateEntityFiles — merged entity pass (EntityProcess.java:421-660)", () => {
  it("flattens the component closure and extends the generated base class", () => {
    const mechUnit = file("MechUnit.ts");
    expect(mechUnit).toContain("export class MechUnit extends Unit implements Unitc, Mechc, Healthc, Entityc, Posc, Teamc {");
    // Fields of the base's closure are shadowed (Java `:341,376`); MechComp's are not.
    expect(mechUnit).toContain("baseRotation: number = 0;");
    expect(mechUnit).toContain("walkTime: number = 0;");
    expect(mechUnit).not.toContain("  health: number = 0;");
    // Private fields are copied in as protected (`:367`) even though the base class
    // omits them (`:188`).
    expect(mechUnit).toContain("protected added: boolean = false;");
    // Static fields keep their modifier (`:353-356`).
    expect(mechUnit).toContain("static hitDuration: number = 9;");
    // `@Import`ed fields emit nothing at all.
    expect(mechUnit).not.toContain("elevation: number = 0;");
  });

  it("puts the shared fields and index members on the abstract base class", () => {
    const base = file("Unit.ts");
    expect(base).toContain("export abstract class Unit implements Unitc, Healthc, Entityc, Posc, Teamc, IndexableEntity__unit {");
    for (const field of ["health", "maxHealth", "dead", "id", "x", "y", "team", "elevation", "drowned"]) {
      expect(base).toContain(`  ${field}: `);
    }
    expect(base).toContain("protected index__unit: number = -1;");
    expect(base).toContain("setIndex__unit(index: number): void {");

    // Java builds the base class with fields only (`:176-213`) and leans on Java's rule
    // that an abstract class need not implement the interfaces it declares. TypeScript has
    // no such rule — `abstract class Unit implements Unitc, …` must *declare* every member
    // of those interfaces or it is a TS2420, and every `EntityGroup<Unit>` a TS2344. So the
    // base now carries bodyless (`abstract`) declarations for the whole component closure.
    // The base is still a pure field carrier: `setIndex__unit` is the only body it owns.
    const baseClass = classNamed(base, "Unit")!;
    const methods = baseClass.members.filter(ts.isMethodDeclaration);
    const concreteMethodNames = methods
      .filter((member) => !(member.modifiers ?? []).some((modifier) => modifier.kind === ts.SyntaxKind.AbstractKeyword))
      .map((member) => member.name.getText());
    expect(concreteMethodNames).toEqual(["setIndex__unit"]);

    // Declared in component-closure order — `UnitComp`, then its dependencies
    // (`HealthComp`, `EntityComp`, `PosComp`, `TeamComp`); `update()` collides and keeps
    // the first owner's position (`:437-613`).
    expect(methods.map((member) => member.name.getText())).toEqual([
      "isGrounded",
      "drownFloor",
      "isValid",
      "healthf",
      "update",
      "killed",
      "kill",
      "heal",
      "isAdded",
      "add",
      "remove",
      "set",
      "trns",
      "dst",
      "cheating",
      "inFogTo",
      "setIndex__unit",
    ]);
    expect(baseClass.members.filter(ts.isPropertyDeclaration).map((member) => member.name.getText())).toEqual([
      "index__unit",
      "elevation",
      "drowned",
      "health",
      "maxHealth",
      "dead",
      "id",
      "x",
      "y",
      "team",
    ]);
  });

  it("merges same-signature methods into one body with labels per component", () => {
    // `update()` exists in both EntityComp and HealthComp; the void-with-several-bodies
    // case wraps each body in a label (`:493,588-601`).
    const update = file("MechUnit.ts").slice(file("MechUnit.ts").indexOf("  update(): void {"));
    expect(update).toContain("  update(): void {\n    health: {\n      this.health = Math.min(this.health, this.maxHealth);\n    }\n  }");
  });

  it("prefers the @Replace implementation over the base one", () => {
    // UnitComp.drownFloor (drowned ? 0 : -1) is replaced by MechComp's.
    expect(file("MechUnit.ts")).toContain("return this.elevation > 0.5 ? -1 : 0;");
    expect(file("MechUnit.ts")).not.toContain("return this.drowned ? 0 : -1;");
    expect(file("UnitEntity.ts")).toContain("return this.drowned ? 0 : -1;");
  });

  it("prefers the implementation with the longest dependency chain when priorities tie", () => {
    // `healthf()` is declared by HealthComp (2 deps) and BuildingComp (4 deps).
    expect(file("Building.ts")).toContain("return this.maxHealth === 0 ? 0 : this.health / this.maxHealth;");
  });

  it("injects group index bookkeeping into add/remove (EntityProcess.java:499-514)", () => {
    const building = file("Building.ts");
    expect(building).toContain("if (this.added === true) return;");
    expect(building).toContain("this.index__build = Groups.build.addIndex(this);");
    expect(building).toContain("Groups.build.removeIndex(this, this.index__build);");
    expect(building).toContain("this.index__build = -1;");
  });

  it("places an entity in its groups and honours excludeGroups", () => {
    // BuildingComp carries Entityc in its closure, so `all` would match — except that
    // `BuildingComp.java:53` declares `excludeGroups = ["all"]`.
    expect(file("Building.ts")).toContain("IndexableEntity__build");
    expect(file("Building.ts")).not.toContain("IndexableEntity__all");
    expect(file("Building.ts")).not.toContain("index__all");
    // MechUnit has UnitComp, which `all` excludes; it stays in `unit`.
    expect(file("MechUnit.ts")).not.toContain("index__all");
    expect(file("Unit.ts")).toContain("IndexableEntity__unit");
    // PosTeam's closure is only TeamComp/PosComp: no Entityc, so no `all`.
    expect(file("PosTeam.ts")).not.toContain("index__all");
  });

  it("writes the legacy branch with no extra members, extending the non-legacy class", () => {
    const legacy = file("MechUnitLegacyNova.ts");
    expect(legacy).toContain("export class MechUnitLegacyNova extends MechUnit implements Unitc, Mechc, Healthc, Entityc, Posc, Teamc {");
    for (const member of ["health", "baseRotation", "index__unit", "walkExtend", "isValid"]) {
      expect(legacy).not.toContain(member);
    }
    expect(legacy).toContain('return "MechUnitLegacyNova#" + this.id;');
  });

  it("emits serialize()/classId()/create() for every entity", () => {
    expect(file("Building.ts")).toContain("serialize(): boolean {\n    return false;\n  }");
    expect(file("MechUnit.ts")).toContain("serialize(): boolean {\n    return true;\n  }");
    expect(file("MechUnit.ts")).toContain("classId(): number {");
    expect(file("MechUnit.ts")).toContain("static create(): MechUnit {");
    expect(file("MechUnit.ts")).toContain("protected constructor() {}");
  });

  it("is deterministic", () => {
    const again = generateEntityFiles({
      components: model.components,
      entityDefs: model.entityDefs,
      groups: DEFAULT_GROUPS,
      classIds,
      inputRoot: fixturesRoot,
    });
    expect([...again.entries()]).toEqual([...outputs.entries()]);
  });
});

describe("generateEntityMappingFile — EntityProcess.java:776-825", () => {
  const entities = resolveEntities({
    components: model.components,
    entityDefs: model.entityDefs,
    groups: DEFAULT_GROUPS,
    classIds,
    inputRoot: fixturesRoot,
  });
  const mapping = generateEntityMappingFile(entities);

  it("imports every entity class as a value, not only the Entityc type", () => {
    // The `static { … }` block constructs the entities, so each class needs a *value*
    // import; `Entityc` is the only type-only one. Java never has to say this because
    // `mindustry.gen` is a single package — omitted in TS it is a TS2304.
    for (const entity of entities) {
      expect(mapping).toContain(`import { ${entity.name} } from "./${entity.name}.js";`);
    }
    expect(mapping).toContain('import type { Entityc } from "./Entityc.js";');
  });

  it("goes through the entity factory rather than the protected constructor", () => {
    // Java writes `PosTeam::new` (`:812`), which is legal there because the generated
    // constructor is `protected` *and* `EntityMapping` sits in the same package. TS's
    // `protected` has no package scope, so a constructor reference would be a TS2674;
    // the entity's own `create()` factory is the way in, and Java's intent — "do not
    // `new` an entity from outside" — is preserved rather than traded away.
    for (const entity of entities) {
      expect(mapping).toContain(`${entity.name}.create()`);
    }
    expect(mapping).not.toContain("() => new ");
  });
});

describe("entity resolution invariants", () => {
  it("rejects duplicate field names across the closure", () => {
    const duplicated: ComponentModel[] = model.components.map((component) =>
      component.compName === "UnitComp"
        ? {
            ...component,
            fields: [...component.fields, { name: "health", type: "number", initializer: "0", readonly: false, imported: false, sync: false, static: false, private: false }],
          }
        : component,
    );
    expect(() =>
      generateEntityFiles({
        components: duplicated,
        entityDefs: model.entityDefs,
        groups: DEFAULT_GROUPS,
        classIds,
        inputRoot: fixturesRoot,
      }),
    ).toThrow(/redefines a field in entity/);
  });

  it("rejects unknown component interfaces", () => {
    const broken = [{ ...model.entityDefs[0], componentRefs: ["Nope"] }];
    expect(() =>
      resolveEntities({
        components: model.components,
        entityDefs: broken,
        groups: DEFAULT_GROUPS,
        classIds,
        inputRoot: fixturesRoot,
      }),
    ).toThrow(EntityGenError);
  });

  it("reports ambiguous implementations when priorities tie", () => {
    const first = model.components.find((c) => c.compName === "HealthComp")!;
    const second = model.components.find((c) => c.compName === "MechComp")!;
    const clash = { ...second, compName: "ClashComp", fields: [], methods: first.methods.map((m) => ({ ...m, owner: "ClashComp" })) };
    expect(() => mergeMethods([first, clash])).toThrow(/Ambiguous implementations/);
  });
});
